### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by Dario-Ciceri** [AllPartsCombined/Leap-Animatronic-Hand#1]
Assets\Scripts\SerialCommunication.cs(4,17): error CS0234: The type or namespace name 'Ports' does not exist in the namespace 'System.IO' (are you missing an assembly reference?)

Assets\Scripts\FingerManager.cs(69,12): error CS0246: The type or namespace name 'Finger' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\FingerManager.cs(9,12): error CS0246: The type or namespace name 'Controller' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\SerialCommunication.cs(11,12): error CS0246: The type or namespace name 'Parity' could not be found (are you missing a using directive or an assembly reference?)

Assets\Scripts\SerialCommunication.cs(14,13): error CS0246: The type or namespace name 'SerialPort' could not be found (are you missing a using directive or an assembly reference?)

**Comment by AllPartsCombined** [comment]
You'll need to set your project to use .NET 4 to fix the Serial related issues. In Unity, go to Edit>Project Settings>Player>Other Settings and change API Compatibility Level to .NET 4.x.

The Finger and Controller are part of the Leap Motion SDK, so importing the Leap packages should resolve those errors.
